// <auto-generated />
using System;
using GameOpsMini.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameOpsMini.Api.Migrations
{
    [DbContext(typeof(GameOpsDbContext))]
    partial class GameOpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameOpsMini.Api.Entities.MonitoredServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port")
                        .IsUnique();

                    b.ToTable("monitored_servers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Host = "127.0.0.1",
                            Name = "DummyGameServer-1",
                            Port = 7777
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Host = "127.0.0.1",
                            Name = "DummyGameServer-2",
                            Port = 7778
                        });
                });

            modelBuilder.Entity("GameOpsMini.Api.Entities.ServerStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MonitoredServerId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredServerId", "CheckedAt");

                    b.ToTable("server_status_histories", (string)null);
                });

            modelBuilder.Entity("GameOpsMini.Api.Entities.ServerStatusHistory", b =>
                {
                    b.HasOne("GameOpsMini.Api.Entities.MonitoredServer", "MonitoredServer")
                        .WithMany("StatusHistories")
                        .HasForeignKey("MonitoredServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredServer");
                });

            modelBuilder.Entity("GameOpsMini.Api.Entities.MonitoredServer", b =>
                {
                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
